# Generated by Django 2.2.4 on 2020-04-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submityourtask',
            name='image',
            field=models.ImageField(blank=True, upload_to='tasks'),
        ),
    ]
