# Generated by Django 2.2.4 on 2020-04-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0002_auto_20200415_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submityourtask',
            name='image',
        ),
    ]
