# Generated by Django 2.2.4 on 2020-04-15 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0003_remove_submityourtask_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submityourtask',
            old_name='address1',
            new_name='address',
        ),
    ]
