# Generated by Django 2.2.4 on 2020-04-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0004_auto_20200415_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmitYourTask',
            new_name='SubmitTask',
        ),
    ]
